MPPIPlannerROS:

  GeneralSettings:

    global_frame: ""  # if left null it will be the same as global_costmap frame
    local_frame: ""   # if left null it will be the same as local_costmap frame

    num_iterations: 1   # number of iterations solving the Path Integral problem 
    batch_size: 1000    # number of propagated trajectories
    time_steps: 60      # horizon length of the propagation ( prediction_time = model_dt*time_steps )
    num_retry: 4        # number of retries when the solution fails (all generated trajectories collide)
    control_offset: 1   # offset to choose the control commands to send

    goal_tolerance: 0.5   # [m] tolerance for considering we have reached the goal 
    plan_shift: 1.5       # [m] meters to shift plan to avoid planning inside the robot's footprint 

    use_splines: false        # whether to interpolate the received global plan with splines
    use_local_planner: true   # whether to use an extra layer of planning (local planner navfn)

    model_dt: 0.05        # [s] integration delta time 
    temperature: 0.3      # Path Integral parameter: Selectiveness of trajectories by their costs (closer to 0, "more" we take into consideration controls with less cost | high values lead to just taking the mean of all trajectories)
    gamma: 0.05           # Path Integral parameter: A trade-off between smoothness (high) and roughness (low).

  Constraints:
    max_vx: 0.75         # [m/s]
    min_vx: -0.75        # [m/s]

    max_vy: 0.5         # [m/s]
    min_vy: -0.5        # [m/s]

    max_wz: 0.1         # [rad/s] 
    min_wz: -0.1        # [rad/s] 

  MotionModel: "BicycleKin" # ["Ackermann", "BicycleKin", "Holonomic"]

  Ackermann: 
    min_radius: 3.0     # [m]

  SteeringModel: 
    length: 1.0         # [m]

  NoiseGeneration:
    std_vx: 0.3         # [m/s]
    std_vy: 0.3         # [m/s]
    std_wz: 0.1         # [rad/s] 

  Critics:
    Goal:
      active: true
      power: 1
      weight: 1.0
      threshold: 1.5

    GoalAngle:
      active: true
      power: 1
      weight: 1.0
      threshold: 1.5

    PathDist:
      active: false
      power: 2
      weight: 5.0
      threshold: 1.0
      stride: 2

    Twirling:
      active: false
      power: 1
      weight: 10.0

    Forward:
      active: false
      power: 1
      weight: 10.0
    
    PathFollow:
      active: true
      power: 1
      weight: 10.0
      threshold: 1.0
      offset_from_furthest: 3

    PathAngle:
      active: true
      power: 1
      weight: 25.0
      threshold: 1.0
      offset_from_furthest: 3
      angle_threshold: 150.0

    Obstacles:
      active: true
      power: 1
      weight: 50.0
      threshold: 1.0
      repulsive_weight: 0.0
      collision_cost: 100000.0
      collision_margin_dist: 0.5

  Visualization:
    batch_stride: 100   # stride for visualizing less trajectories (rendering all trajectories can lead to too much overhead)
    time_stride: 3      # stride for the horizon length
    default_z: 0.2      # default z value for the visualized trajectories
    scale: 0.05         # markers scale
